package is.lab.mapita.modelo;
// Generated 08-feb-2019 13:44:51 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private Tema tema;
     private Usuario usuario;
     private String descripcion;
     private double longitud;
     private double latitud;
     private Set coments = new HashSet(0);
     
    public Marcador() {
    }

	
    public Marcador(int idmarcador, String descripcion, double longitud, double latitud) {
        this.idmarcador = idmarcador;
        this.descripcion = descripcion;
        this.longitud = longitud;
        this.latitud = latitud;
    }
    public Marcador(int idmarcador, Usuario usuario, Tema tema, String descripcion, double longitud, double latitud, Set coments) {
       this.idmarcador = idmarcador;
       this.tema = tema;
       this.usuario= usuario;
       this.descripcion = descripcion;
       this.longitud = longitud;
       this.latitud = latitud;
       this.coments=coments;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public Set getComents() {
        return coments;
    }

    public void setComents(Set coments) {
        this.coments = coments;
    }



}


